
package ru.gretchen.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuadraticEquationService", targetNamespace = "http://services.ws.equation/", wsdlLocation = "http://localhost:8080/Service/QuadraticEquation?wsdl")
public class QuadraticEquationService_Service
    extends Service
{

    private final static URL QUADRATICEQUATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUADRATICEQUATIONSERVICE_EXCEPTION;
    private final static QName QUADRATICEQUATIONSERVICE_QNAME = new QName("http://services.ws.equation/", "QuadraticEquationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Service/QuadraticEquation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUADRATICEQUATIONSERVICE_WSDL_LOCATION = url;
        QUADRATICEQUATIONSERVICE_EXCEPTION = e;
    }

    public QuadraticEquationService_Service() {
        super(__getWsdlLocation(), QUADRATICEQUATIONSERVICE_QNAME);
    }

    public QuadraticEquationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUADRATICEQUATIONSERVICE_QNAME, features);
    }

    public QuadraticEquationService_Service(URL wsdlLocation) {
        super(wsdlLocation, QUADRATICEQUATIONSERVICE_QNAME);
    }

    public QuadraticEquationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUADRATICEQUATIONSERVICE_QNAME, features);
    }

    public QuadraticEquationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuadraticEquationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuadraticEquationService
     */
    @WebEndpoint(name = "QuadraticEquationPort")
    public QuadraticEquationService getQuadraticEquationPort() {
        return super.getPort(new QName("http://services.ws.equation/", "QuadraticEquationPort"), QuadraticEquationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuadraticEquationService
     */
    @WebEndpoint(name = "QuadraticEquationPort")
    public QuadraticEquationService getQuadraticEquationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.ws.equation/", "QuadraticEquationPort"), QuadraticEquationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUADRATICEQUATIONSERVICE_EXCEPTION!= null) {
            throw QUADRATICEQUATIONSERVICE_EXCEPTION;
        }
        return QUADRATICEQUATIONSERVICE_WSDL_LOCATION;
    }

}
