
package ru.gretchen.soapclient;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QuadraticEquationService", targetNamespace = "http://service.quadraticequationsolving.gretchen.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuadraticEquationService {


    /**
     * 
     * @param a
     * @param b
     * @param c
     * @return
     *     returns ru.gretchen.soapclient.Response
     */
    @WebMethod(action = "urn:result")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solveEquation", targetNamespace = "http://services.ws.equation/", className = "ru.gretchen.soapclient.SolveEquation")
    @ResponseWrapper(localName = "solveEquationResponse", targetNamespace = "http://services.ws.equation/", className = "ru.gretchen.soapclient.SolveEquationResponse")
    public Response solveEquation(
        @WebParam(name = "a", targetNamespace = "")
        double a,
        @WebParam(name = "b", targetNamespace = "")
        double b,
        @WebParam(name = "c", targetNamespace = "")
        double c);

}
